---
- name: SHIPPING APPLICATION FOR ROBOSHOP
  hosts: SHIPPING
  become: yes
  vars:
    MYSQL_PASS: "RoboShop@1"
  tasks:
    - name: INSTALLING MAVEN
      dnf:
        name: maven
        state: present

    - name: CONFIGURE APPLICATION USER
      user:
        name: roboshop

    - name: CREATE APP DIRECTORY
      file:
        path: /app
        state: directory

    - name: DOWNLOAD APPLICATION CODE INTO APP DIRECTORY
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp

    - name: UNZIP APP CODE
      unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: INSTALL MAVEN PACKAGES
      shell: "{{ item }}"
      loop:
        - mvn clean package
        - mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: COPY SHIPPING SERVICE FILE
      copy:
        src: /home/centos/Anisible-Roboshop-Application/shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: RELOAD SYSTEMD DAEMON
      systemd:
        daemon_reexec: yes

    - name: START SHIPPING SERVICE
      systemd:
        name: shipping
        state: started

    - name: MYSQL INSTALLATION
      dnf:
        name: mysql
        state: present

    - name: CHECKING CITIES INFO
      shell: "mysql -h mysql.gonepudirobot.online -uroot -p'{{ MYSQL_PASS }}' -sN -e 'SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = ''cities'';'"
      register: CITIES_INFO

    - name: PRINT CITIES COUNT
      debug:
        msg: "{{ CITIES_INFO.stdout }}"

    - name: LOAD THE DATA WHEN CITIES COUNT ZERO
      shell: "mysql -h mysql.gonepudirobot.online -uroot -p'{{ MYSQL_PASS }}' < /app/schema/shipping.sql"
      when: CITIES_INFO.stdout == "0"

    - name: RESTART SHIPPING SERVICE
      systemd:
        name: shipping
        state: restarted
