---
- name: SHIPPING APPLICATION FOR ROBOSHOP
  hosts: SHIPPING
  become: yes

  tasks:
    - name: INSTALLAING MAVEN
      dnf:
        name: maven
        state: present

    - name: CONFIGURE APPLICATION USER
      user:
        name: roboshop

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: absent
    
    - name: CREATE APP DIRECTORY
      file:
        path: /app
        state: directory

    - name: DOWNLOAD APPLICATION CODE INTO APP DIRECTORY
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp

    - name: UNZIP APP CODE
      unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: INSTALL MAVEN PACAKAGES
      args:
        chdir: /app
      shell: {{ item }}
      loop:
      - mvn clean package
      - mv target/shipping-1.0.jar shipping.jar
      

    - name: COPY SHIPPING SERVICE FILE
      copy:
        src: /home/centos/Anisible-Roboshop-Application/shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: RELOAD SYSTEMD DAEMON
      ansible.builtin.systemd:
        daemon_reexec: yes

    - name: START SHIPPING SERVICE
      ansible.builtin.systemd:
        name: shipping
        state: started

    - name: RESTART SHIPPING SERVICE
      systemd:
        name: shipping
        state: restarted
